# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 11:55
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
            ],
            options={
                'verbose_name': 'End User Account',
                'proxy': True,
                'verbose_name_plural': 'End User Accounts',
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Account',
                'proxy': True,
                'verbose_name_plural': 'Staff Accounts',
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
